In [1]:
import numpy as np

In [5]:
def n_size_ndarray_creation(n, dtype=np.int):
    X=np.array(range(n**2), dtype=dtype).reshape(n,n)
    return X

n_size_ndarray_creation(5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
def zero_or_one_or_empty_ndarray(shape, type, dtype=np.int):
    if type==99:
        X=np.empty(shape=shape, dtype=dtype)
    if type==0:
        X=np.zeros(shape=shape, dtype=dtype)
    if type==1:
        X=np.ones(shape=shape, dtype=dtype)
    
    return X

print(zero_or_one_or_empty_ndarray((2,3,4), type=99))
print(zero_or_one_or_empty_ndarray((2,3,4), type=0))
print(zero_or_one_or_empty_ndarray((2,3,4), type=1))


[[[1063872312        549         50          0]
  [         0          0          0          0]
  [         0          0 1852990827  942566501]]

 [[ 842479670  758592054 1697657957  892548141]
  [1631071538  959275569  811688291 1717711672]
  [ 775172914 1952543859 1600484213 1970496882]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [46]:
def change_shape_of_ndarray(X, n_row):
    if n_row==1:
        return X.flatten()
    else:
        return X.reshape(n_row,-1)

X=np.ones((4,2),dtype=np.int)
print(change_shape_of_ndarray(X, 1))
print(change_shape_of_ndarray(X, 4))

[1 1 1 1 1 1 1 1]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [68]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim==1:
        X_1=X_1.reshape(1,-1)
    if X_2.ndim==1:
        X_2=X_2.reshape(1,-1)
    return np.concatenate((X_1, X_2), axis=axis)

A=np.arange(16).reshape(4,4)
print(A)

B=np.arange(32).reshape(4,-1)
print(B)

concat_ndarray(A, B, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 24, 25, 26, 27, 28, 29, 30, 31]])

In [75]:
def normalize_ndarray(X, axis, dtype=np.float32):
    X=X.astype(np.float32)
    n_row, n_column = X.shape
    
    if axis==99:
        x_mean=np.mean(X)
        x_std=np.std(X)
        Z=(X-x_mean)/x_std
    if axis==0:
        x_mean=np.mean(X,0).reshape(1,-1)
        x_std=np.std(X,0).reshape(1,-1)
        Z=(X-x_mean)/x_std
    if axis==1:
        x_mean=np.mean(X,1).reshape(n_row,-1)
        x_std=np.std(X,1).reshape(n_row,-1)
        Z=(X-x_mean)/x_std
        
    return Z
        
X=np.arange(12, dtype=np.float32).reshape(6,2)
print(normalize_ndarray(X, axis=99))
print(normalize_ndarray(X, axis=0))
print(normalize_ndarray(X, axis=1))

[[-1.593255   -1.3035723 ]
 [-1.0138896  -0.7242068 ]
 [-0.4345241  -0.14484136]
 [ 0.14484136  0.4345241 ]
 [ 0.7242068   1.0138896 ]
 [ 1.3035723   1.593255  ]]
[[-1.46385 -1.46385]
 [-0.87831 -0.87831]
 [-0.29277 -0.29277]
 [ 0.29277  0.29277]
 [ 0.87831  0.87831]
 [ 1.46385  1.46385]]
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]
 [-1.  1.]]


In [76]:
def save_ndarray(X, filename="test.npy"):
    npy_array=np.load(file="npy_test.npy")
    
X=np.arange(32, dtype=np.float32).reshape(4, -1)
save_ndarray(X)

In [77]:
def boolean_index(X, condition):
    condition=eval(str("X")+condition)
    return np.where(condition)

X=np.arange(32, dtype=np.float32)
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [85]:
def find_nearest_value(X, target_value):
   return X[np.argmin(np.abs(X-target_value))]

X=np.random.uniform(0,1,5)
print(X)
find_nearest_value(X, 0.3)

[0.97035348 0.68857976 0.63117818 0.12901907 0.38245759]


0.38245758593721413

In [98]:
def get_n_largest_values(X, n):
    X=X[np.argsort(X)[::-1][:n]]
    return X

X=np.random.uniform(0,1,5)
print(X)
get_n_largest_values(X, 3)

[0.41490142 0.51133165 0.72732299 0.00805639 0.11749668]


array([0.72732299, 0.51133165, 0.41490142])