In [2]:
import numpy as np

test_array = np.array([1,4,5,8], float)
print(test_array)
print(type(test_array[3]))
print(test_array.dtype) #배열 저네의 데이터타입
print(test_array.shape)

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [3]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [4]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [7]:
#32비트 = 4바이트
np.array([[1,2,3], [4.5,5,6]], dtype=np.float32).nbytes 

24

In [8]:
#8비트 = 1바이트
np.array([[1,2,3], [4.5,5,6]], dtype=np.int8).nbytes 

6

In [9]:
#64비트 = 8바이트
np.array([[1,2,3], [4.5,5,6]], dtype=np.float64).nbytes 

48

In [10]:
test_matrix=[[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [12]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [13]:
test=np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [15]:
test.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [16]:
test_example=np.array([[1,2,3],[4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
test_example[0][0]

1

In [18]:
test_example[0,0]

1

In [19]:
test_example[0,0]=12
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [21]:
test_example[0][0]=5
test_example

array([[5, 2, 3],
       [4, 5, 6]])

In [22]:
test_example=np.array([
    [1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [23]:
test_example[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [24]:
test_example[1,:2]

array([1, 2])

In [26]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [27]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [28]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [29]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [31]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [33]:
np.empty((3,5))

array([[ 0.00000000e+000,  9.76647024e-312,  9.76647024e-312,
        -3.80445996e-311,  9.76655854e-312],
       [ 9.76655854e-312,  9.76655854e-312,  9.76655854e-312,
         9.76655854e-312,  5.43472210e-323],
       [ 0.00000000e+000,  3.95252517e-323,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000]])

In [34]:
test_matrix=np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [35]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [36]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(3,5,k=2) #k는 start index을를설정...

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
matrix=np.arange(9).reshape(3,3)
np.diag(matrix) #대각행렬 값 추출

array([0, 4, 8])

In [43]:
np.diag(matrix, k=1) #대각행렬 값 추출 시 start index 설정

array([1, 5])

In [44]:
np.random.uniform(0,1,10).reshape(2,5) #균등분포

array([[0.87848338, 0.74438226, 0.28687559, 0.99295314, 0.78420378],
       [0.29872416, 0.34838725, 0.0603448 , 0.01843044, 0.54479307]])

In [45]:
np.random.normal(0,1,10).reshape(2,5) #정규분포

array([[-1.3564783 , -1.10225688, -0.94129084, -0.31898109, -0.14838101],
       [ 0.20358775, -0.76641099,  1.69360437, -0.12534071,  0.19095511]])

In [46]:
test_array=np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
test_array.sum(dtype=np.float)

55.0

In [49]:
test_array=np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
test_array.sum(axis=1) #
,test_array.sum(axis=0) #

array([15, 18, 21, 24])

In [52]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [55]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [57]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [58]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [59]:
test_a=np.array([[1,2,3],[4,5,6]], float)

In [60]:
test_a+test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [61]:
test_a*test_a #matrix상 같은 위치에 있는 element끼리 곱함

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [63]:
test_a=np.arange(1,7).reshape(2,3)
test_b=np.arange(7,13).reshape(3,2)
test_a.dot(test_b) #Dot product

array([[ 58,  64],
       [139, 154]])

In [64]:
test_a=np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
test_matrix=np.array([[1,2,3],[4,5,6]], float)
scalar=3
test_matrix+scalar #브로드캐스팅... 스칼라연산할 때 유용

array([[4., 5., 6.],
       [7., 8., 9.]])

In [68]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [70]:
np.any(a>5), np.any(a<0)

(True, False)

In [71]:
np.all(a>5), np.all(a<10)

(False, True)

In [72]:
a=np.array([1,3,0], float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [73]:
b=np.array([True,False,True], bool)
np.logical_not(b)

array([False,  True, False])

In [76]:
c=np.array([False,True,False], bool)
np.logical_or(b,c)

array([ True,  True,  True])

In [77]:
a

array([1., 3., 0.])

In [78]:
np.where(a>0, 3, 2) #true이면 3, false이면 2 반환

array([3, 3, 2])

In [79]:
np.where(a>0) #index값 반환

(array([0, 1], dtype=int64),)

In [80]:
a=np.array([1,np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [81]:
np.isfinite(a)

array([ True, False, False])

In [84]:
a=np.arange(100)
np.argmax(a), np.argmin(a) #최대, 최소값의 index 반환

(99, 0)

In [85]:
a=np.array([[1,2,4,7],[9,88,6,45], [9,76,3,4]])
np.argmax(a, axis=1), #row 기준 최대값 index
np.argmin(a, axis=0)  #col 기준 최소값 index

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

In [87]:
test_array=np.array([1,4,0,2,3,8,9,7], float)
test_array>3

array([False,  True, False, False, False,  True,  True,  True])

In [88]:
test_array[test_array>3]

array([4., 8., 9., 7.])

In [91]:
condition=test_array<3
test_array[condition]

array([1., 0., 2.])

In [92]:
A=np.array([12,13,14,12,16,14,11,10,9])
B=A<15
B.astype(np.int)

array([1, 1, 1, 1, 0, 1, 1, 1, 1])

In [93]:
a=np.array([2,4,6,8], float)
b=np.array([0,0,1,3,2,1], int)
a[b] #fancy index : array를 index value로 사용

array([2., 2., 4., 8., 6., 4.])

In [94]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [96]:
a=np.array([[1,4], [9,16]], float)
b=np.array([0,0,1,1,0], int)
c=np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [98]:
a = np.loadtxt("./populations.txt")
a[:10]

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.]])

In [99]:
a_int=a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [100]:
np.savetxt('int_data.csv', a_int, delimiter=",")

In [102]:
np.save("npy_test", arr=a_int)

In [103]:
npy_array=np.load(file="npy_test.npy")
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])